version: '3'
services:
  database:
    build: ./database
    command: postgres -c shared_preload_libraries=pgaudit -c config_file=/etc/postgresql.conf
    container_name: base-database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: zaq1@WSX
      POSTGRES_DB: base
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
      - ./database/postgresql.conf:/etc/postgresql.conf
    ports:
      - "5444:5432"
