version: '3.4'
services:

  database:
    container_name: prod-database-app
    build: ../database
    command: postgres -c shared_preload_libraries=pgaudit -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cderfv
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/pgdata
    volumes:
      - ../database/pgdata:/var/lib/postgresql/pgdata
      - ../database/postgresql.conf:/etc/postgresql.conf
    restart: on-failure

  api:
    container_name: prod-api-app
    build:
      context: ../api
      dockerfile: ./Dockerfile
      target: deploy
    volumes:
      - ../files:/home/app/files
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "DATASOURCES_DATABASE_HOST=database"
    restart: on-failure

  ui:
    container_name: prod-ui-app
    build:
      context: ../ui
      dockerfile: ./Dockerfile
      target: deploy
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
#
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
