version: '3.4'
services:

  database:
    container_name: base-db
    build: ../database
    command: postgres -c shared_preload_libraries=pgaudit -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cderfv
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/pgdata
    volumes:
      - ../database/pgdata:/var/lib/postgresql/pgdata
      - ../database/postgresql.conf:/etc/postgresql.conf
#    restart: on-failure

  api:
    container_name: base-api
    build:
      context: ../api
      dockerfile: ./Dockerfile
      target: deploy
    volumes:
      - ../files:/home/app/files
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
#    restart: on-failure
    depends_on:
      - database

  ui:
    container_name: base-ui
    build:
      context: ../ui
      dockerfile: ./Dockerfile
      target: deploy
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
#    restart: on-failure
