version: '3.4'
services:

  database:
    container_name: db
    build: ../database
    command: postgres -c shared_preload_libraries=pgaudit -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: zaqwsx
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/pgdata
    volumes:
      - ../database/pgdata:/var/lib/postgresql/pgdata
      - ../database/postgresql.conf:/etc/postgresql.conf
    ports:
      - "5444:5432"

  api:
    container_name: api
    build:
      context: ../api
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - ../api/:/home/app/
      - ../files:/home/app/files
    environment:
      - "SPRING_PROFILES_ACTIVE=dev, swagger"
    depends_on:
      - database
#    command: sh -c  "./gradlew --stop && ./gradlew bootRun"
#    command: ["./gradlew", "clean", "bootRun"]
    command: ["gradle", "bootRun"]
    ports:
      - "9000:9000"

  ui:
    container_name: ui
    build:
      context: ../ui
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - ../ui/:/usr/src/app/
    environment:
      - "APIPROXY=api"
    command: sh -c  "npm i && npm start"
    ports:
      - "3000:3000"
