# ===================================================================
# Spring Boot configuration for the "dev" profile.
# ===================================================================
logging:
  level:
    ROOT: INFO
    web: DEBUG
    base.api: DEBUG
    base.api.mappers:
      AuthMapper: INFO
    base.api.domain.diaries.DiaryDao.selectUser: INFO

datasources:
  database:
    username: admin
    password: zaqwsx
    port: 5444
    schema: app
    host: localhost
  migration:
    locations: ["classpath:/db/migration", "classpath:/db/mock"]
    cleanOnValidationError: true
    cleanOnStart: true

spring:
  profiles:
    include:
      - swagger
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
