server:
  port: 9000

spring:
  application:
    name: base-app
  profiles:
    active: dev
  datasource:
    initialization-mode: always
  flyway:
    locations: "classpath:/db/migration"
  jackson:
    time-zone: "Europe/Warsaw"
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: "piorowskiapp"
#    password: "matpioapp"
#    properties:
#      mail:
#        smtp:
#          auth: true
#          connectiontimeoute: 5000
#          timeout: 5000
#          writetimeout: 5000
#          starttls:
#            enable: true

mail:
  host: smtp.gmail.com
  port: 587
  username: "piorowskiapp@gmail.com"
  password: "matpioapp"
  from: "Aplikacja Codeito"
  debug: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-actual-param-name: false
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    lazy-load-trigger-methods: ""
  type-handlers-package: base.api.config.mybatis
