# ===================================================================
# Spring Boot configuration for the "test" profile.
# ===================================================================
logging:
  level:
    ROOT: INFO
    web: DEBUG
    base.api: DEBUG
    base.api.mappers:
      AuthMapper: INFO
    base.api.domain.diaries.DiaryDao.selectUser: INFO

datasources:
  database:
    username: admin
    password: cderfv
    port: 5432
    schema: app
  migration:
    locations: ["classpath:/db/migration", "classpath:/db/mock"]
    cleanOnValidationError: false
    cleanOnStart: false
