# ===================================================================
# Spring Boot configuration for the "prod" profile.
# ===================================================================
#TODO - set prod logging
logging:
  level:
    ROOT: INFO
    web: DEBUG
    base.api: DEBUG
    base.api.mappers:
      AuthMapper: INFO
    base.api.domain.diaries.DiaryDao.selectUser: INFO

datasources:
  database:
    host: database
    port: 5432
    username: admin
    password: cderfv
    schema: app
  migration:
    locations: ["classpath:/db/migration"]
    cleanOnValidationError: false
    cleanOnStart: false
storage:
  location: "/home/app/files"
