# ===================================================================
# Spring Boot configuration for the "test" profile.
# ===================================================================
#TODO - set test logging
logging:
  level:
    ROOT: INFO
    web: DEBUG
    base.api: DEBUG
    base.api.mappers:
      AuthMapper: INFO
    base.api.domain.diaries.DiaryDao.selectUser: INFO

datasources:
  database:
    host: database
    port: 5432
    username: admin
    password: cderfv
    schema: app
  migration:
    locations: ["classpath:/db/migration", "classpath:/db/mock"]
    cleanOnValidationError: false
    cleanOnStart: false
