# ===================================================================
# Spring Boot configuration for the "test" profile.
# ===================================================================
logging:
  level:
    ROOT: WARN
    base.api: DEBUG
    base.api.mappers:
      AuthMapper: INFO

datasources:
  database:
    username: admin
    password: xswedc
    port: 5432
    schema: app
    host: database

spring:
  flyway:
    locations: "classpath:/db/migration, classpath:/db/test"
